// Add protact With Java

let protactMastere = [
  {
    id: 1,
    title: "Esprit Ruffle Shirt",
    price: 16.56,
    imges: "../img/cloth/1.jpeg",
    imgesOne: "../img/cloth/1.jpeg",
    imgesTwo: "../img/cloth/2.jpeg",
    imgesThree: "../img/cloth/3.jpeg",
    size: 15,
    for: "woman",
    quint: 1,
    isMe: "n",
  },
  {
    id: 2,
    title: "Herschel supply",
    price: 35.31,
    imges: "../img/cloth/4.jpeg",
    imgesOne: "../img/cloth/4.jpeg",
    imgesTwo: "../img/cloth/5.jpeg",
    imgesThree: "../img/cloth/9.jpeg",
    size: 22,
    for: "woman",
    quint: 1,
    isMe: "n",
  },
  {
    id: 3,
    title: "Only Check Trouser",
    price: 251.3,
    imges: "../img/clithM/3.png",
    imgesOne: "../img/cloth/10.jpeg",
    imgesTwo: "../img/cloth/12.jpeg",
    imgesThree: "../img/cloth/1.jpeg",
    size: 45,
    for: "man",
    quint: 1,
    isMe: "n",
  },
  {
    id: 4,
    title: "Classic Trench Coat",
    price: 9500,
    imges: "../img/clithM/4.png",
    imgesOne: "../img/cloth/8.jpeg",
    imgesTwo: "../img/cloth/9.jpeg",
    imgesThree: "../img/cloth/3.jpeg",
    size: 56,
    for: "woman",
    quint: 1,
    isMe: "n",
  },
  {
    id: 5,
    title: "Front Pocket Jumper",
    price: 45.6,
    imges: "../img/clithM/5.png",
    imgesOne: "../img/cloth/10.jpeg",
    imgesTwo: "../img/cloth/2.jpeg",
    imgesThree: "../img/cloth/8.jpeg",
    size: 22,
    for: "woman",
    quint: 1,
    isMe: "n",
  },
  {
    id: 6,
    title: "Vintage Inspired Classic",
    price: 93.5,
    imges: "../img/clithM/6.png",
    imgesOne: "../img/cloth/2.jpeg",
    imgesTwo: "../img/cloth/6.jpeg",
    imgesThree: "../img/cloth/3.jpeg",
    size: 11,
    for: "man",
    quint: 1,
    isMe: "n",
  },
  {
    id: 7,
    title: "Shirt in Stretch Cotton",
    price: 51.2,
    imges: "../img/clithM/7.png",
    imgesOne: "../img/cloth/1.jpeg",
    imgesTwo: "../img/cloth/2.jpeg",
    imgesThree: "../img/cloth/3.jpeg",
    size: 22,
    for: "woman",
    quint: 1,
    isMe: "n",
  },
  {
    id: 8,
    title: "Pieces Metallic Printed",
    price: 51.2,
    imges: "../img/clithM/8.png",
    imgesOne: "../img/cloth/1.jpeg",
    imgesTwo: "../img/cloth/2.jpeg",
    imgesThree: "../img/cloth/9.jpeg",
    size: 22,
    for: "woman",
    quint: 1,
    isMe: "n",
  },
  {
    id: 9,
    title: "convaers ",
    price: 51.2,
    imges: "../img/clithM/9.png",
    imgesOne: "../img/cloth/7.jpeg",
    imgesTwo: "../img/cloth/15.jpeg",
    imgesThree: "../img/cloth/6.jpeg",
    size: 40,
    for: "all",
    quint: 1,
    isMe: "n",
  },
  {
    id: 10,
    title: "Femme T-Shirt In Stripe",
    price: 15.2,
    imges: "../img/clithM/10.png",
    imgesOne: "../img/cloth/1.jpeg",
    imgesTwo: "../img/cloth/5.jpeg",
    imgesThree: "../img/cloth/3.jpeg",
    size: 22,
    for: "woman",
    quint: 1,
    isMe: "n",
  },
  {
    id: 11,
    title: "Herschel supply",
    price: 152.2,
    imges: "../img/clithM/11.png",
    imgesOne: "../img/cloth/1.jpeg",
    imgesTwo: "../img/cloth/2.jpeg",
    imgesThree: "../img/cloth/8.jpeg",
    size: 22,
    for: "man",
    quint: 1,
    isMe: "n",
  },
  {
    id: 12,
    title: "Herschel supply",
    price: 51.2,
    imges: "../img/clithM/12.png",
    imgesOne: "../img/cloth/1.jpeg",
    imgesTwo: "../img/cloth/9.jpeg",
    imgesThree: "../img/cloth/3.jpeg",
    size: 22,
    for: "man",
    quint: 1,
    isMe: "n",
  },
  {
    id: 13,
    title: "T-Shirt with Sleeve",
    price: 125.2,
    imges: "../img/clithM/13.png",
    imgesOne: "../img/cloth/1.jpeg",
    imgesTwo: "../img/cloth/4.jpeg",
    imgesThree: "../img/cloth/3.jpeg",
    size: 22,
    for: "woman",
    quint: 1,
    isMe: "n",
  },
  {
    id: 14,
    title: "Pretty Little Thing",
    price: 51.2,
    imges: "../img/clithM/14.png",
    imgesOne: "../img/cloth/1.jpeg",
    imgesTwo: "../img/cloth/9.jpeg",
    imgesThree: "../img/cloth/4.jpeg",
    size: 35 & 45,
    for: "woman",
    quint: 1,
    isMe: "n",
  },
  {
    id: 15,
    title: "Mini Silver Mesh Watch",
    price: 250.0,
    imges: "../img/clithM/15.png",
    imgesOne: "../img/cloth/1.jpeg",
    imgesTwo: "../img/cloth/7.jpeg",
    imgesThree: "../img/cloth/3.jpeg",
    size: 10,
    for: "woman",
    quint: 1,
  },
];
